fixtures:
  repositories:
    "stdlib":
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref:  "5.2.0"
    "yum":
      repo: "git://github.com/voxpupuli/puppet-yum.git"
      ref:  "v3.1.1"
    "yumrepo_core":
      repo: "git://github.com/puppetlabs/puppetlabs-yumrepo_core.git"
      ref:  "1.0.3"
    "g_firewall":
      repo: "git://github.com/glorpen/puppet-g_firewall.git"
      ref:  "v0.3.1"
    "firewall":
      repo: "git://github.com/puppetlabs/puppetlabs-firewall.git"
      ref:  "1.15.3"
    "sudo":
      repo: "git://github.com/saz/puppet-sudo.git"
      ref:  "v6.0.0"
    "cron":
      repo: "git://github.com/voxpupuli/puppet-cron.git"
      ref:  "v1.3.1"
    "network":
      repo: "git://github.com/example42/puppet-network.git"
      ref:  "v3.5.0"
    "hosts":
      repo: "git://github.com/glorpen/puppet-hosts.git"
      ref:  "v1.1.0"
    "concat":
      repo: "git://github.com/puppetlabs/puppetlabs-concat.git"
      ref:  "5.3.0"
    "augeas_core":
      repo: "git://github.com/puppetlabs/puppetlabs-augeas_core.git"
      ref:  "1.0.4"
    "ssh":
      repo: "git://github.com/saz/puppet-ssh.git"
      ref:  "v5.0.0"
